pipelines:
  default:
    - step:
        image: node:14.15.5-alpine3.10
        caches:
          - node
        name: Run linter and tests
        script:
          - cp .env.dist .env
          - npm install
          - npm run lint
          - npm run coverage
  custom:
    deploy-staging:
      - step:
          name: deploy to staging
          image: tshio/frontend-aws-cli
          script:
            - npm ci
            - npm run build
            - cd build
            - aws s3 sync . s3://$APP_BUCKET --delete
            - aws cloudfront create-invalidation --distribution-id $APP_DISTRIBUTION_ID --paths "/*"
